---
- hosts: win-hardening
  tasks:
    - name: "Set maximum password age"
      community.windows.win_security_policy:
        section: System Access
        key: MaximumPasswordAge
        value: 90
    
    - name: "Set minimum password age"
      community.windows.win_security_policy:
        section: System Access
        key: MinimumPasswordAge
        value: 14

    - name: "Set password complexity"
      community.windows.win_security_policy:
        section: System Access
        key: PasswordComplexity 
        value: 1

    - name: "Set password min length"
      community.windows.win_security_policy:
        section: System Access
        key: MinimumPasswordLength 
        value: 8

    - name: "Set password history count"
      community.windows.win_security_policy:
        section: System Access
        key: PasswordHistorySize 
        value: 2

    - name: "Disable remote registry"
      ansible.windows.win_service:
        name: RemoteRegistry
        state: stopped
        start_mode: disabled



    
