---
- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Install notepad++
  win_chocolatey:
    name: notepadplusplus
    state: present

- name: Install 7zip 
  win_chocolatey:
    name: 7zip
    state: present

- name: Install adobe reader 
  win_chocolatey:
    name: adobereader
    state: present

- name: Install .Net 3.5
  ansible.windows.win_optional_feature:
    name: NetFx3
    state: present
